name: build moOSe kernel

on:
  push:
    branches: [main, ]
  pull_request:

jobs:
  build:
    name: build kernel
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: moose.img
          path: moose.img