name: build moOSe kernel

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    name: build kernel
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Buildx
        run: docker buildx build -f Dockerfile --output . .

      - name: check binary
        run: ls -la

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: moose.img
          path: moose.img