name: build moOSe kernel

on:
  push:
    branches: [main, cicd]
  pull_request:

jobs:
  formatting:
    env:
      SRCS: moose
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          extensions: 'h,c'
          clangFormatVersion: 12
  build:
    name: build kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Buildx
        run: |
          docker buildx build --output . .

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: moose.img
          path: moose.img
